---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-role-sudoers

  vars:
    sudoers_files:
    - path: "/etc/sudoers"
      defaults:
        - "!visiblepw"
        - "always_set_home"
        - "match_group_by_gid"        # NOTE: for sudo>=1.8.18
        - "always_query_group_plugin" # NOTE: maintains sudo pre-1.8.15 group behavior
        - "env_reset"
        - secure_path:
            - "/sbin"
            - "/bin"
            - "/usr/sbin"
            - "/usr/bin"
        - env_keep:
            - "COLORS"
            - "DISPLAY"
            - "HOSTNAME"
            - "HISTSIZE"
            - "KDEDIR"
            - "LS_COLORS"
            - "MAIL"
            - "PS1"
            - "PS2"
            - "QTDIR"
            - "USERNAME"
            - "LANG"
            - "LC_ADDRESS"
            - "LC_CTYPE"
            - "LC_COLLATE"
            - "LC_IDENTIFICATION"
            - "LC_MEASUREMENT"
            - "LC_MESSAGES"
            - "LC_MONETARY"
            - "LC_NAME"
            - "LC_NUMERIC"
            - "LC_PAPER"
            - "LC_TELEPHONE"
            - "LC_TIME"
            - "LC_ALL"
            - "LANGUAGE"
            - "LINGUAS"
            - "_XKB_CHARSET"
            - "XAUTHORITY"
      user_specifications:
        - users:
            - "root"
          hosts:
            - "ALL"
          operators:
            - "ALL"
          commands:
            - "ALL"
        - users:
            - "%wheel"
          hosts:
            - "ALL"
          operators:
            - "ALL"
          commands:
            - "ALL"
      include_directories:
        - "/etc/sudoers.d"
      
    - path: "/etc/sudoers.d/90-cloud-init-users"
      user_specifications:
        - users:
            - "ec2-user"
          hosts:
            - "ALL"
          operators:
            - "ALL"
          commands:
            - "NOPASSWD:ALL"